### PR TITLE
Rust: Clippy

### PR DESCRIPTION
**Pull request by droogmic**
I found some more clippy issues.

The strange part: clippy in my IDE caught these, but running `cargo clippy` manually did not.

@dabreegster can you trying running `cargo clippy` on `main` and let me know what you get?

### CODE REVIEW

**Comment by dabreegster** [comment]
I don't get any clippy warnings on `main` at all. `cargo clippy --version` says `clippy 0.1.58 (02072b4 2022-01-11)`

**Review by dabreegster — APPROVED** [review]
The changes it suggested look good though

**Comment by droogmic** [comment]
> I don't get any clippy warnings on `main` at all. `cargo clippy --version` says `clippy 0.1.58 (02072b4 2022-01-11)`

I also cannot, and I am on 0.1.60

I wonder what makes the vscode environment different...

**Comment by droogmic** [comment]
declining, I think all of clippy was fixed in the other PR

**Pull request closed without merging**
