### PR TITLE
Rust: Refactor RoadBuilder and LaneBuilder

### PR DESCRIPTION
**Pull request by droogmic**
These are two quite big structs, so we begin a refactor by moving them out of mod to allow for better increments

### CODE REVIEW

**Comment by dabreegster** [comment]
Should we merge one of the big bus PRs before creating more merge conflicts?

**Comment by droogmic** [comment]
> Should we merge one of the big bus PRs before creating more merge conflicts?

I find it's a slippery slope to block integration due to big PRs. I want to see if we can start splitting @BudgieInWA's concepts into even smaller pieces.

**Review by dabreegster — APPROVED** [review]
I _think_ you're mostly just moving code around here? Sadly git didn't detect it as a move/copy

**Comment by droogmic** [comment]
> I _think_ you're mostly just moving code around here? Sadly git didn't detect it as a move/copy

I... think so as well. Honestly don't remember 100%. I think I split a file in two. Refactoring is one weakness in git review methodology :P

**Pull request merged**
