### PR TITLE
Readme format add docs webview

### PR DESCRIPTION
**Pull request by tordans**
Minor changes and additions to the readme.

### CODE REVIEW

**Review by dabreegster — APPROVED** [review]
Thank you for the cleanup and more clear explanation of how the demo is pushed!

**Comment by enzet** [comment]
Sorry, but I don't agree with header changes.  The readme file was deliberately using `===` and `---` syntax for first and second level heading and never used `##`, so it was consistent.  I subjectively consider them more human-readable.

Don't you mind if I'll get headers back?

Anyway, thank you for contributing! Just my personal preference.

**Comment by dabreegster** [comment]
> Don't you mind if I'll get headers back?

No preference from my end

**Comment by tordans** [comment]
>Don't you mind if I'll get headers back?

I don't mind. 

I also don't agree. :-) Using dashes for all headlines is what I see in most `.md` files. It is super easy to scan and understand (and learn): one hash = h1, two hashes h2 and so on. With the `=` and `-` I need to look up which is what. And then I am wondering if the length of the line needs to be aligned with the word… And when scanning I see those as separators `--- `, not headline indicators.

**Comment by droogmic** [comment]
I enjoy adding fuel to a pedantic discussion, so my opinion:

- markdown is a terrible markup language (see any of the many blog posts: https://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/), last I did research I think I liked asciidoc the most.

- if we do use markdown, it is because it is the default on github, so let's just do what they say: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by enzet** [comment]
Well OK, I give up. :)

GitHub Docs look convincing.

**Pull request merged**
