### PR TITLE
Rust: Enable Benchmarking

### PR DESCRIPTION
**Pull request by droogmic**
If we can configure the settings correctly, a bot should comment here with a nice looking table.

### CODE REVIEW

**Comment by droogmic** [comment]
@dabreegster, I don't think I have permissions to change this repo's settings?

**Comment by dabreegster** [comment]
I set role = admin, let me know if that works

**Comment by droogmic** [comment]
> I set role = admin, let me know if that works

Ah, I see now that I am running into this.

If I have more time to play with this I will try to do something for fun in 2 steps.

**Comment by droogmic** [comment]
For now, if you want to check benchmarks from a fork, you need to open up the logging.

**Pull request merged**
